name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso crítico 1: Instalar el binario de cloudflared en el runner de GitHub
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      # 2. Ejecutar el despliegue con el ProxyCommand integrado
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.nforero.com
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          # Pasamos el comando directamente a la acción para que el contenedor lo use
          proxy_command: /usr/local/bin/cloudflared access ssh --hostname ssh.nforero.com
          script: |
            cd /var/www/store && \
            git pull origin main && \
            cd api && npm install && pm2 restart api && \
            cd ../tiendaOnline && npm install && npm run build && \
            cd ../adminPanel && npm install && npm run build